### ISSUE TITLE
[Dupe] Obvious portal duplication

### ISSUE THREAD

**Issue by slava110** [mrp-v2/VersatilePortals#10]
You can easily duplicate portal blocks and existing world controls with this mod. You just need another method to teleport to this dimension.
Easiest example (with vanilla nether):
1. Bind world control to nether dimension
2. Build portal in overworld near to nether portal
3. Teleport via VersatilePortal and destroy portal in nether (it will generate free portal blocks + existing world control)
4. Teleport back to overworld via nether portal
5. Repeat

**Comment by mrp-v2** [comment]
This is the same as with nether portals. In theory, you can farm obsidian with them. This is working as intended.
