### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Iashar** [mrp-v2/VersatilePortals#5]
[latest.log](https://github.com/mrp-v2/VersatilePortals/files/6210333/latest.log)

Random crash, I've not even build a portal yet.

Not sure what could cause it, but then I'm using many mods. Hope this is useful in making things more stable in some way.

**Comment by mrp-v2** [comment]
I've uploaded a new version which logs a warning instead of crashing when the portal data isn't found, which is what happened in your log. Try using version `1.16.5-3.1.0.0-forge` and see if it fixes the issue.
